### ISSUE TITLE
Server not reachable

### ISSUE THREAD

**Issue by lsorba** [Swing-team/pendulums-web-client#103]
Dear pendulum team, 

I am an happy user of your desktop app to log my time.
This morning the app is in offline mode, it can't seem to connect to the server (connection timeout)

I also tried to reach https://app.pendulums.io/ and https://pendulums.io/ but they are not reachable.

Can you please check that your server is reachable ?

Thank you in advance,

All the best,
Laurent

**Comment by mohammadrafigh** [comment]
Thanks for your kind words. It was a short maintenance down time by our service provider. It's up and working again.

**Comment by lsorba** [comment]
Thank you !
