### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JullietV** [Swing-team/pendulums-web-client#11]
When I started testing the app first I noticed is that it has not any kind of documentation, so I wasn't sure of what the app really does or how it does that. 
I wasn't sure of what to do either. 
Adding a documentation of the app, even if it's simple would be a really good help.

**Comment by mohammadrafigh** [comment]
Thank you @JullietV , in next release we are going to add more details in our landing page. also we will create a "how to use" page and a tutorial video too.

**Comment by mohammadrafigh** [comment]
this is fixed and will be available with next version scheduled for next week.
