### ISSUE TITLE
System does not send confirmation emails, in the registration process. So, no new users are possible at the moment. 

### ISSUE THREAD

**Issue by tnmedien** [Swing-team/pendulums-web-client#122]

**Comment by mohammadrafigh** [comment]
Have you checked spam directory?

**Comment by tnmedien** [comment]
Sure, and I have tried it with different emails.

Von: Mohammad Rafigh ***@***.***>
Gesendet: Mittwoch, 20. September 2023 16:40
An: Swing-team/pendulums-web-client ***@***.***>
Cc: Tobias Neumann ***@***.***>; Author ***@***.***>
Betreff: Re: [Swing-team/pendulums-web-client] System does not send confirmation emails, in the registration process. So, no new users are possible at the moment. (Issue #122)

Have you checked spam directory?

**Comment by mohammadrafigh** [comment]
Yes I see. For some weird reason the email service provider has temporarily listed our emails as spam which is not correct. I'm contacting their support to fix the problem, thanks for reporting.

**Comment by tnmedien** [comment]
Thank you very much. Hopefully they will solve this, soon. Then I can add our next team member.

Btw., you have a great and self explaining UI. I think, the best on the market.
So, I will also do monthly contributions, because that is just fair.

Von: Mohammad Rafigh ***@***.***>
Gesendet: Mittwoch, 20. September 2023 17:49
An: Swing-team/pendulums-web-client ***@***.***>
Cc: Tobias Neumann ***@***.***>; Author ***@***.***>
Betreff: Re: [Swing-team/pendulums-web-client] System does not send confirmation emails, in the registration process. So, no new users are possible at the moment. (Issue #122)


Yes I see. For some weird reason the email service provider has temporarily listed our emails as spam which is not correct. I'm contacting their support to fix the problem, thanks for reporting.

**Comment by mohammadrafigh** [comment]
Aww thanks for your kind words :), I really appreciate it.
It was just a DNS record change that I needed to apply, It takes 1 hour at maximum to reflect the changes, I will update you when it's fixed.

**Comment by tnmedien** [comment]
Thank you!

Von: Mohammad Rafigh ***@***.***>
Gesendet: Mittwoch, 20. September 2023 18:39
An: Swing-team/pendulums-web-client ***@***.***>
Cc: Tobias Neumann ***@***.***>; Author ***@***.***>
Betreff: Re: [Swing-team/pendulums-web-client] System does not send confirmation emails, in the registration process. So, no new users are possible at the moment. (Issue #122)


Aww thanks for your kind words :), I really appreciate it.
It was just a DNS record change that I needed to apply, It takes 1 hour at maximum to reflect the changes, I will update you when it's fixed.

**Comment by mohammadrafigh** [comment]
It's now fixed, please let me know if you had any other issues and close this issue if your issue is resolved.

**Comment by tnmedien** [comment]
Solved very fast. :-)
