### ISSUE TITLE
Cancel account

### ISSUE THREAD

**Issue by kamishiro** [Swing-team/pendulums-web-client#14]
I created an account on app.pendulums.io - I wish to cancel it, but cannot find any way to do so.

**Comment by mohammadrafigh** [comment]
dear @kamishiro,
it's sad to hear that you don't like Pendulums, it would be great if you share with us why you don't like it?
this feature is scheduled but for now we can do it for you manually, please provide the email you registered with, then we will confirm the action with an email to you.
