### ISSUE TITLE
Account removal request

### ISSUE THREAD

**Issue by vanntile** [Swing-team/pendulums-web-client#16]
I wish to remove my account at vanntile@protonmail.com 
The service looks good, however, it was not the productivity app I was looking for

**Comment by mohammadrafigh** [comment]
dear @vanntile 
it's sad to hear that Pendulums is not the service you were looking for, it would be great if you share with us what we can do to improve Pendulums?
account removal feature is scheduled for next 2 releases but for now we can do it for you manually. we will confirm the action using an email.

**Comment by vanntile** [comment]
I was looking for something really specific on my needs - automatic time accounting and adding to activities categories (before or after), and a value for each time period and a stat system. Now I have something that requires my input and my time to update.

**Comment by kaibutsu** [comment]
Hi,
as it's not implemented yet - could you delete my account, too? kaibutsu@posteo.org
Thanks!
