### ISSUE TITLE
[Improvement] Text cursor on "untitled project" by default

### ISSUE THREAD

**Issue by javiermv** [Swing-team/pendulums-web-client#18]
When clicking "Add project" the typing cursor is not positioned in the text box for the project's name. Using the desktop interface, this forces the user to click on the text box before the new name can be defined.

**Comment by mohammadrafigh** [comment]
thanks for your suggestion, I agree with you for new project but not edit page. I will add it tonight it would be available with next release (1.0.0) in 1-2 days.

**Comment by mohammadrafigh** [comment]
Fixed
