### ISSUE TITLE
contact form on the website is broken

### ISSUE THREAD

**Issue by muppeth** [Swing-team/pendulums-web-client#22]
Seems like your contact form is broken. I tried to send you an email but the form just gets stuck doing nothing when you press "Send".

**Comment by mohammadrafigh** [comment]
Thanks @muppeth we have got your email, but the form doesn't show a suitable message according to that. we will fix it. thanks for reporting.

**Comment by muppeth** [comment]
cool. and sorry for sending it twice :P

**Comment by mohammadrafigh** [comment]
It's fixed and the results would be available with next release in a few days.
