### ISSUE TITLE
"no internet connection" error

### ISSUE THREAD

**Issue by kerneltux0** [Swing-team/pendulums-web-client#25]
I'm getting a "no internet connection" error.
Running Ubuntu 18.04, I just completed an OS update, and running Pendulums 1.01
I'm also getting "server not found" when I go to https://pendulums.io/

**Comment by mohammadrafigh** [comment]
thank you dear @kerneltux0. sorry for the down time. there was a problem at our VPS provider it's fixed now, please confirm this and then I will close this issue.

**Comment by kerneltux0** [comment]
I figured it was something like that, but wasn't sure if anyone knew. Everything's working now. :-)
