### ISSUE TITLE
Take to much CPU/RAM

### ISSUE THREAD

**Issue by gagarine** [Swing-team/pendulums-web-client#26]
The app take way to much CPU and RAM on my MacBook air for what i does (a time tracker). Should be a native app. Somethings around 0.1% CPU while in background and 25Mb ram would be acceptable.

![Screenshot 2019-06-29 at 14 17 35](https://user-images.githubusercontent.com/164074/60383970-d746b880-9a78-11e9-99d2-deb83c7abee3.png)

**Comment by mohammadrafigh** [comment]
Thanks for reporting this issue. it's weird to see this regarding to CPU usage! the memory is normal for an Electron app but the CPU shouldn't be like that. we will investigate this more. we may be able to replace Electron with other lightweight cross platform solutions, but making a native app is not a high priority thing currently. Eventhough we can help you or anyone else who is interested to make a native app or fix issues on current Electron app.

**Comment by mohammadrafigh** [comment]
@gagarine We have updated Pendulums to 1.1.0 with latest Electron and we had a lot of performance improvements. can you please try and check if this issue has been fixed for you?

**Comment by mohammadrafigh** [comment]
Closed due to inactivity
