### ISSUE TITLE
gTLD is not accepted as email address

### ISSUE THREAD

**Issue by cookiengineer** [Swing-team/pendulums-web-client#27]
When registering an account, gTLD domains from 2013 and later are not allowed.

In my case `somethingsomething(doesnt matter)` @ `artificial.engineering` was not allowed as a valid email.

Which means in particular that this RegExp is a wrong assumption, as gTLDs can have an unlimited amount of characters after the `.`: https://github.com/Swing-team/pendulums-web-client/blob/97e55c44007479666f76cd80e09f6c9a9d86a6c7/src/app/authentication/sign-up/sign-up.component.ts#L5

**Comment by mohammadrafigh** [comment]
oh cool! thanks for your notice. are you going to make a PR or we should schedule it for next release?

**Comment by cookiengineer** [comment]
I do not think that the RegEx js a valid solution for this. Since gTLDs came out there has to be either a whitelist based on the [public suffix list](https://publicsuffix.org/list/) maintained by mozilla or a compiled regex based on their data. Most other solutions are pretty much invalid, as they don't reflect real TLDs.

As I would be a first-time user, I have no clue what the expected solution would look like. My personal opinion says that a RegEx is unmaintainable in its complexity when it comes to TLDs, but you as the authors have to decide on that.

(Haven't been able to use pendulums yet because I only own gTLDs)

**Comment by mohammadrafigh** [comment]
@Ashkan4472 where is your commit on this? is it fixed?
