### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by mdantasjr99** [Swing-team/pendulums-web-client#28]
Hi guys. I need some help. When I tried to export the CSV file and open with LibreOffice, the columns "started at" and "stopped at" does not show the time, it shows a big number:

startedAt            |  stoppedAt
1565033670350 | 1565039505559
1565030759917 | 1565032578047

I tried to format the cell, but nothing changes.

I need to show time like: 07:00 | 08:00.

I can do it manually, copping the times from the app, but in most cases is a lot of tasks to copy, I'm spending much time with that.

**Comment by mohammadrafigh** [comment]
The times are shown based on Unix timestamp (milliseconds). so you can convert them in LibreOffice with some Math. But you are right we should show a human readable time in CSV.
We are working on our new release with some features like sorting projects and notes. I schedule this issue for this release.

**Comment by mohammadrafigh** [comment]
It's fixed and would be available in a few days with new release.
