### ISSUE TITLE
Frequent "Did you forget to stop your time?!" emails

### ISSUE THREAD

**Issue by arschficken** [Swing-team/pendulums-web-client#29]
Am I using the app incorrectly? I just select a project and press the play button. But for each new project I do this for, team@pendulums.io soon sends an email with the following body:

> It seems you have a current activity and you are disconnected for 15 mins.
> 
> you can stop your time if you forgot to do it.

I've received three of these emails in the past hour.

To begin with, I don't expect to receive emails from a service that I use primarily via an Android app. Email and apps are two separate paradigms.

More to the point, I'm going to be working on tasks for more than 15 minutes at a time. It should be OK to start a task and not stop it for several hours, or even half a day. If the app thinks I've made a mistake, it should ask me via a notification.

Is there a way to disable these emails?

**Comment by mohammadrafigh** [comment]
Thanks for using Pendulums,

In Android, when the app goes to background, Pendulums loses its connection
with server and the app assumes that you left Pendulums without stopping
your activity which is incorrect. To resolve this problem we should
implement a background service which keeps track of activity and
connection. The notification features would work correctly on desktop and
web apps but not in Android.
Sorry for this annoying issue, I try to fix it for next release which would
be due in next few days. For now you can disable this feature from your
profile settings (tap on your profile image in side menu).

**Comment by mohammadrafigh** [comment]
The fix has been committed and would be available in Pendulums 1.1.0

**Comment by arschficken** [comment]
Pirooz bashid!
