### ISSUE TITLE
Donate from Iran

### ISSUE THREAD

**Issue by Ssisakhti** [Swing-team/pendulums-web-client#3]
how do I donate you from Iran?

**Comment by Ssisakhti** [comment]
It is awesome. You may wonder if look at pay.ir or zarinpal.com for Iranian payment gateway.

**Comment by mohammadrafigh** [comment]
We had a contact with Zarinpal. we will investigate more between pay.ir and zarinpal.com. thanks for your suggestions.

**Comment by mohammadrafigh** [comment]
@arminghm is it possible to customize payment amount dynamically based on donator's request with Zarinpal?

**Comment by Ssisakhti** [comment]
And check this out:
https://idpay.ir/mimalef70

**Comment by mohammadrafigh** [comment]
cool! I like it! thanks!

**Comment by arminghm** [comment]
@Ssisakhti thanks, it's great. 
@mohammadrafigh I'll investigate.

**Comment by mohammadrafigh** [comment]
@Ssisakhti here is the idpay link: https://idpay.ir/pendulums

we will add it to app and landing page for next release at the end of this week.

thanks for your suggestions.

**Comment by mohammadrafigh** [comment]
@Ashkan4472 it seems the commit is not referenced here.

@Ssisakhti it's already deployed thanks. I close this issue.
