### ISSUE TITLE
[Improvement] Project children

### ISSUE THREAD

**Issue by PierreRamoin** [Swing-team/pendulums-web-client#33]
Hi,
First of all, thanks for the tool, I've been looking for this kind of stuff for a while, without finding anything satisfying!

The only thing I would love to see is being able to create project children (tasks in my case).

Do you think that can be possible to implement?
Pierre

**Comment by arminghm** [comment]
Actually we planned to add project management tools to Pendulums or integrate them with Pendulums, but we need funds and donations to do that 😉
