### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by arnljot** [Swing-team/pendulums-web-client#35]
Seems like pendulums.io is down again?

**Comment by MikhailPavlov** [comment]
Started using pendulums few weeks ago. I like it's lightweightness. It's disappointing that I can't export my stats without internet connection.

**Comment by arnljot** [comment]
For me this was at the worst possible time, on a monday when I report my billable hours for the previous week.

**Comment by muppeth** [comment]
Is there any official statement on what going on? Seems like it's down the entire weekend.

**Comment by mohammadrafigh** [comment]
We are really really sorry for this down time. the service provider where our servers located, had issues with internet connection; so the Pendulums was not accessible and It should be accessible now. we planned to move our servers to another VPS provider ASAP. so please be patient a few days, then the Pendulums would be a lot faster than before with our new servers.

**Comment by arnljot** [comment]
Servers are up, and @mohammadrafigh provided an insight as to what had happened.

**Comment by mohammadrafigh** [comment]
We are done with relocating our servers. With a more powerful hardware and faster network and a well known VPS provider we can expect a better performance and less downtime.
