### ISSUE TITLE
Pendulums: "There is no internet connection!"

### ISSUE THREAD

**Issue by uint8** [Swing-team/pendulums-web-client#36]
Not sure if pendulums if offline for some reason? I'm online (writing this bug request) and have tried from various computers with the same results.

![Screenshot from 2019-11-21 09-37-50](https://user-images.githubusercontent.com/14079732/69362073-a98a2800-0c42-11ea-92e0-98be8668eec2.png)

I've been using it for time-tracking across devices and have been loving it! Would be great if it came back online.. 

Thanks!

**Comment by mohammadrafigh** [comment]
sorry for this, the issue is related to #35 , this week we will migrate our server to another location with a better hardware spec, with more bandwidth, and faster internet connection, so you can expect a huge speed improvement in 2-3 days. just please be patient.

**Comment by mohammadrafigh** [comment]
We are done with relocating our servers. With a more powerful hardware and faster network and a well known VPS provider we can expect a better performance and less downtime.
