### ISSUE TITLE
"There Is No Internet Connection"

### ISSUE THREAD

**Issue by DSGQR** [Swing-team/pendulums-web-client#4]
**Im on a mac running:**
- macOS High Sierra - version: 10.13.6
- MacBook Pro (Retina, 13-inch, Early 2015)
- Processor 3.1 GHz Inter Core i7
- Memory 16GB 1867 MHz DDR3

Ive been using your software with no apparent issues for about 2 weeks.

Now im constantly prompted with "There Is No Internet Connection"

Everything Im doing is currently connected and working with the internet successfully with the exception of your app.

Please advise...

Thanks in advance,

**Comment by mohammadrafigh** [comment]
thanks for reporting this issue. We will investigate and fix this in next 24hs at maximum. Your activities will remain safe on your device. And will sync when the connection is strong.

Also we planned to migrate our server for better performance in next few weeks.

**Comment by DSGQR** [comment]
Thats it. I was running version 0.4.0.

I didn't realize there wasn't a way to update via the app itself.

I have now re-downloaded 0.4.1 and replaced the older version. It seems to be functioning correctly again.

Thank you.

Also, will there be an iOS app ?

**Comment by mohammadrafigh** [comment]
Cool 👍👍
Auto update is in progress but you will receive a notification in side menu when there is an update available. Also Linux users will receive updates from Snapcraft. Eventhough I agree that we may need an auto update mechanism, we have planned it.

Yes we have an iOS app ready, but we are investigating some legal things with App Store. So we will release iOS version asap.
