### ISSUE TITLE
Feature request: edit/delete entires

### ISSUE THREAD

**Issue by earthbound19** [Swing-team/pendulums-web-client#44]
Is this not a part of the time tracking feature yet? I'm looking for how to do this in the web interface and the desktop client (which seems to simply present a smaller web interface). To be very blunt, time tracking is not a complete feature without the ability to edit time. Editing time entries is elemental to time tracking.

It would be nice, also, if stopping and starting a task would continue the timer on literally the same task, instead of creating a copy of the task with notes. This might be another timekeeping paradigm, where total time is more important than when a task literally started, stopped, started a separate time, and stopped again. Harvest (getharvest dot com) tracks this way by default I think.

**Comment by mohammadrafigh** [comment]
You can edit and remove your entries from activities page. You can navigate
to activities page by clicking on the diagram icon under project name.

Regarding to resuming the same activity, It's already scheduled and would
be added soon. But for now you can see a sum of your daily activities in
activities page.

Please consider that Pendulums is a free and open source project so adding
more features relies on community contributions in code or donations. So
please be patient and we will add a lot of exciting features.
