### ISSUE TITLE
Option to edit

### ISSUE THREAD

**Issue by jarrodmedrano** [Swing-team/pendulums-web-client#46]
Accidentally left timer running for 6 hours and I can't see any way to edit it.

**Comment by mohammadrafigh** [comment]
You can edit your activity by going to activities page for each project
(just press the chart icon near project settings (cog wheel) on the
project. then there is a pen beside each activity.

**Comment by mohammadrafigh** [comment]
Please let me know if your issue has been fixed so I can close this issue.

**Comment by jarrodmedrano** [comment]
Yes but I think it would make sense to have the edit button on the first page next to the clock.

**Comment by mohammadrafigh** [comment]
Yes, we are going to make dashboard more useful in our next release so we can expect a better UX on dashboard. thanks for your opinion. so I close it for now.
