### ISSUE TITLE
feature request: possibility to add activity retroactively when you forgot to start the timer

### ISSUE THREAD

**Issue by bennypr0fane** [Swing-team/pendulums-web-client#47]
I forgot to start the activity timer when I started working and I have a feeling that's gonna happen many more times and for many users, especially if one just got started using time-tracking.
So I'd like the possibility of adding that activity to a project with a time stamp preceding the current time, i.e. when I actually started

**Comment by mohammadrafigh** [comment]
You can currently add a new activity or edit your activity from activities
page. Just press the chart button over project item in your dashboard and
you will be routed to activities page.

**Comment by bennypr0fane** [comment]
Thanks, that's actually what I was looking for!
