### ISSUE TITLE
APK in FDroid?

### ISSUE THREAD

**Issue by dosch** [Swing-team/pendulums-web-client#6]
I wasn't able to find the apk of the android client in FDroid. Did I miss something?

**Comment by mohammadrafigh** [comment]
the APK has been submitted and will be available in F-droid in a few days. if you have downloaded the APK from our website, you should uninstall it and install F-Droid version if you faced signature problems.

**Comment by mohammadrafigh** [comment]
it's now available at: https://f-droid.org/en/packages/team.swing.pendulums/
