### ISSUE TITLE
Cant Create a activity with a different end date

### ISSUE THREAD

**Issue by HawkdotDev** [Swing-team/pendulums-web-client#79]
![Screenshot 2022-01-26 160249](https://user-images.githubusercontent.com/78171603/151147684-08969412-5d6c-4983-9f9e-78518e734b83.png)

Lets say I want to create a activity under a project that has to be completed through more than one day !!
seems like I cant do that.

**Comment by mohammadrafigh** [comment]
Actually you can easily do that but the problem I see in the screenshot is you are trying to make an activity for the future. Using Pendulums you can track your current and previous activities, so you are not able to create a new activity for the future. If you create an activity which was completed in more than 1 day, the app automatically splits the activity through days. for example if you start an activity from Jan 25th at 10PM and finish it at Jan 26th 02AM, the activity would be splitted into 2 activities: 1. 10PM to 11:59PM 2. 00:00AM to 02:00AM.

Please let me know if you're looking for something else.

**Comment by HawkdotDev** [comment]
> Actually you can easily do that but the problem I see in the screenshot is you are trying to make an activity for the future. Using Pendulums you can track your current and previous activities, so you are not able to create a new activity for the future. If you create an activity which was completed in more than 1 day, the app automatically splits the activity through days. for example if you start an activity from Jan 25th at 10PM and finish it at Jan 26th 02AM, the activity would be splitted into 2 activities: 1. 10PM to 11:59PM 2. 00:00AM to 02:00AM.
> 
> Please let me know if you're looking for something else.

I actually wanted to plan a task/project which has several activities inside it. Lets say I plan to add a new feature to pendulum in next 7 days and log the activities of each day inside it ! Is there a feature that I could use to plan events ? that would be really helpful
