### ISSUE TITLE
[enhancement] Local copy or export

### ISSUE THREAD

**Issue by dosch** [Swing-team/pendulums-web-client#8]
Hey,

I have been using your app now for some time and I am really happy with it. So I want to keep on using it. But the data in their is pretty important for me. So is their a way to make a backup, or a local copy at regular intervals, just in case something might happen to your server...

thnx and keep up the great work!

**Comment by mohammadrafigh** [comment]
thank you dear @dosch for being interested. yes it's already scheduled as the most top priority in our backlog. we will consider it in next 2 releases.

for now we are going to fix a lot of issues and add notes/checklist for projects.

**Comment by mohammadrafigh** [comment]
@golarajahangir @Ashkan4472 Please investigate this, we need pdf and excel exports and json backups as well. also importing using backedup json should be feasible.

**Comment by dosch** [comment]
hey team, I am really hoping this feature can be added sometime. Is there still active development on pendulums, or did attention shift?
Especially if pendulums will get lower attention, it would be nice to allow people to obtain a back-up of the data they put in the system

**Comment by mohammadrafigh** [comment]
dear @dosch yes we are working on the next release, it takes some time because we had some changes in our team members. this feature is in progress and I think we can expect a release in 2 weeks.

**Comment by dosch** [comment]
That is great to hear, thank you for your fast response and hard work!

**Comment by mohammadrafigh** [comment]
to update you, we are working on export as JSON and export as CSV for now, we may not be able to provide import for this release which needs more investigation so we postponed it to next 2 releases.

**Comment by mohammadrafigh** [comment]
this is done and will be available with next version scheduled for next week.

although we also planned excel and pdf exports for later releases.

**Comment by dosch** [comment]
Cool beans! But, I can't seem to locate this feature... Where can I find the new export function?

**Comment by mohammadrafigh** [comment]
@dosch we are merging and testing things in develop branch. the feature would be available in next 2-3 days if we don't face a serious bug.

**Comment by mohammadrafigh** [comment]
@dosch it's up now. hope you enjoy it.

**Comment by DrakaSAN** [comment]
Hi @mohammadrafigh , I may be dull, but I can't seems to find the feature, be it in the web, android or linux app.

EDIT: I am dull, there was a "graph" icon under each projects, the export function is on that view in a big, nice button

**Comment by mohammadrafigh** [comment]
Hi dear user
The export is available in activities page under chart
