### ISSUE TITLE
Export activities to Excel

### ISSUE THREAD

**Issue by martin-g** [Swing-team/pendulums-web-client#9]
Hi!

First let me thank you for this nice tool!

I'd like to ask for a new feature: export activities to an Excel file.
My idea is to introduce an "Export" button in the activities view that when clicked creates a new Excel file with the following contents:

|| Date            | Activity name  | Duration       ||
|| October 29 2018 | Some task      | 1:23h          ||
|| October 29 2018 | Another task   | 4:23h          ||
|| [empty]         | [empty]        | Total duration ||

It will be useful to send to clients / managers.

**Comment by arminghm** [comment]
Hi
thank you @martin-g for being interested.
Its already planned and will be done in 2 next release.
I'll close this issue because it is duplicate.

**Comment by martin-g** [comment]
I think #8 is about import/export of the project settings. My issue is about exporting the exporting data.

**Comment by mohammadrafigh** [comment]
@martin-g thanks, I added more details there.

**Comment by mohammadrafigh** [comment]
@martin-g csv and json exports are now available.
